### DISCUSSION TITLE
Can't I connect directly to AWS Bedrock and not openrouter?

### DISCUSSION THREAD

**Discussion by onesider** [alvinunreal/tmuxai#36] [Q&A] [answered]
Hi Guys. 
Can't I use AWS Bedrock or Gemini API Key myself without using openrouter? Do you have any plans to support this?
Thanks.

**Comment by alvinunreal** [comment, marked as answer]
Hey,
Gemini is possible to use via following config:
```
openrouter:
  model: gemini-2.5-pro-preview-06-05
  api_key: XXXX
  base_url: https://generativelanguage.googleapis.com/v1beta/openai/
```
 
 Bedrock doesn't have openai compatible endpoint out of the box.
