### ISSUE TITLE
(local) Ollama as AI backend

### ISSUE THREAD

**Issue by WuerfelDev** [alvinunreal/tmuxai#13]
**Is your feature request related to a problem? Please describe.**
- i don't want to create an online account if its not necessary
- I might have sensitive data
- Company might not allow online AI models

**Describe the solution you'd like**
An option to connect to a local Ollama instead of using OpenRouter

**Describe alternatives you've considered**
\-

**Additional context**
https://github.com/ollama/ollama/blob/main/docs/api.md

**Comment by alvinunreal** [comment]
Updated readme to include instructions for local Ollama.
This would be example config:
```yaml
openrouter:
  api_key: api-key
  model: gemma3:1b
  base_url: http://localhost:11434/v1
```


but it's not tested with it - might need some prompt tuning. 
If anyone is able to test and contribute learnings.
