### ISSUE TITLE
Direct OpenAI Key support

### ISSUE THREAD

**Issue by shinzui** [alvinunreal/tmuxai#6]
The project looks really interesting! However, I'd prefer not to use OpenRouter. Is there any chance you might support using OpenAI keys directly?

**Comment by hbak** [comment]
humbly request Anthropic as well

**Comment by alvinunreal** [comment]
I will add it in the documentation, OpenRouter is actually OpenAI compatible, so you can just change config to have OpenAI base url:

```
openrouter:
  api_key: sk-proj-XXX
  model: o4-mini-2025-04-16
  base_url: https://api.openai.com/v1/
```
